services:
  app:
    container_name: devices-cleanup
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]